# Generated by Django 4.0.3 on 2022-05-24 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quan_type', models.SmallIntegerField(choices=[(0, '心情日记'), (1, '作文杂谈'), (2, '学习资料'), (3, '社团活动'), (4, '兴趣爱好'), (5, '吐槽'), (6, '互助福利社'), (7, '二手转让')], verbose_name='文章类型')),
                ('quan_title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('quan_pic', models.CharField(max_length=100, verbose_name='引用图片链接')),
                ('quan_content', models.TextField(max_length=1000, verbose_name='文章内容或链接')),
                ('quan_tag', models.CharField(max_length=8, verbose_name='标签：建议#开头')),
                ('picture', models.ImageField(blank=True, upload_to='images/', verbose_name='上传照片')),
                ('quan_star', models.IntegerField(default=0)),
                ('quan_read', models.IntegerField(default=0)),
                ('quan_created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('quan_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
    ]
