# Generated by Django 4.0.3 on 2022-05-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quan',
            name='quan_content',
            field=models.TextField(max_length=800, verbose_name='文章内容或链接'),
        ),
        migrations.AlterField(
            model_name='quan',
            name='quan_pic',
            field=models.CharField(blank=True, max_length=38, verbose_name='引用图片链接'),
        ),
        migrations.AlterField(
            model_name='quan',
            name='quan_title',
            field=models.CharField(max_length=30, verbose_name='文章标题'),
        ),
    ]
